/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

// react-native-reanimated has deleted due to the conflicts and errors